Map<String, String> get en => {
  'loginTitle': 'Login',
  'registerTitle': 'Register',
  'textUsernameOrEmail': 'Username or Email',
  'textPassword': 'Password',
  'textRepeatPassword': 'Repeat Password',
  'textDontHaveAccount': 'Don\'t have an account? Sign Up',
  'textUsername': 'Username',
  'textEmail': 'Email',
  'textSelectYourGender': 'Select your gender',
  'textMale': 'Male',
  'textFemale': 'Female',
  'textOther': 'Other',
  'textName': 'Name',
  'textSurname': 'Surname',
  'textSelectYourLevel': 'Select your level',
  'textSelectYourPosition': 'Select your position',
  'textRightPosition': 'Right',
  'textBackhandPosition': 'Backhand',
  'textIndifferentPosition': 'Indiferent',
  'homeTitle': 'Paddle',
  'textKeepMeLogged': 'Keep me logged in',
  'textFriends': 'Friends',
  'textAddFriend': 'Add friend',
  'textMyFriends': 'My friends',
  'titleProfile': 'Profile',
  'textToday': 'Today',
  'textTomorrow': 'Tomorrow',
  'textAfterTomorrow': 'After tomorrow',
  'textAppName': 'PADEL IT',
  'textSportManagement': 'SPORT MANAGEMENT',
  'textProfile': 'Profile',
  'textTournaments': 'Tournaments',
  'textSettings': 'Settings',
  'textMatches': 'Matches',
  'textDay': 'Day',
  'textCreate': 'Create',
  'textNewMatch': 'New Match',
  'textHour': 'Hour',
  'errorAlreadyJoined': 'You are already joined to the match!',
  'textJoined': 'Joined',
  'textLevel': 'Level',
  'textYouNeedToJoin': 'For challenge you need to join first!',
  'textChallengeFriend': 'Challenge friends',
  'textTeam': 'Team',
  'textSetResult': 'Set Result',
  'textLeaveGame': 'Leave game',
  'textYourLeftTheGame': 'You left the game',
  'textYouHaveInvitedAllYourFriends': 'Could not find friends for invite!',
  'textInvitationSent': 'Invitation sent',
  'textCouldNotSendInvitation': 'Could not send invitation',
  'textInvitations': 'Invitations',
  'textPlay': 'Play!',
  'textRecord': 'Record',
  'roundOfSixteen': 'Round Of 16',
  'quarterFinals': 'Quarter Finals',
  'semiFinals': 'Semi-Final',
  'final': 'Final',
  'textLoading': 'Loading',
  'textMyPosition': 'My position',
  'textChangeTheme': 'Change Theme',
  'textLogout': 'Logout',
  'textAdministration': 'Administration',
  'textWeeklyMatchesVolume': 'Weekly Matches Volume',
  'textNoMatchesFound': 'No matches found',
  'textCreateUser': 'Create User',
  'textUpdateUser': 'Update User',
  'textCompanySettings': 'Company Settings',
  'textWeeklySellsVolume': 'Weekly sells volume',
  'textRefreshStatistics': 'Refresh Statistics',
  'textOptions': 'Options',
  'textMatchPrice': 'Match Price',
  'textCheckFields': 'Error, check the fields',
  'textCompanyUpdated': 'Settings updated correctly',
  'textContinue': 'Continue',
  'textCancel': 'Cancel',
  'textSaveSettings': 'Save settings',
  'textAreYouSureSaveSettings': 'Do you want to save the settings?',
};
