Map<String, String> get es => {
  'loginTitle': 'Iniciar Sesión',
  'registerTitle': 'Registrarse',
  'textUsernameOrEmail': 'Usuario o Email',
  'textPassword': 'Contraseña',
  'textRepeatPassword': 'Repetir Contraseña',
  'textDontHaveAccount': '¿No tienes una cuenta? Registrate',
  'textUsername': 'Nombre de usuario',
  'textEmail': 'Email',
  'textSelectYourGender': 'Selecciona tu género',
  'textMale': 'Chico',
  'textFemale': 'Chica',
  'textOther': 'Otro',
  'textName': 'Nombre',
  'textSurname': 'Apellido',
  'textSelectYourLevel': 'Elige tu nivel',
  'textSelectYourPosition': 'Elige tu posicion',
  'textRightPosition': 'Derecha',
  'textBackhandPosition': 'Revés',
  'textIndifferentPosition': 'Indiferente',
  'homeTitle': 'Pádel',
  'textKeepMeLogged': 'Mantener la sesión iniciada',
  'textFriends': 'Amigos',
  'textAddFriend': 'Añadir amigo',
  'textMyFriends': 'Mis amigos',
  'titleProfile': 'Perfil',
  'textToday': 'Hoy',
  'textTomorrow': 'Mañana',
  'textAfterTomorrow': 'Pasado mañana',
  'textAppName': 'PADEL IT',
  'textSportManagement': 'GESTIÓN DEPORTIVA',
  'textTournaments': 'Torneos',
  'textSettings': 'Ajustes',
  'textMatches': 'Partidas',
  'textDay': 'Día',
  'textCreate': 'Crear',
  'textNewMatch': 'Nueva Partida',
  'textHour': 'Hora',
  'errorAlreadyJoined': 'Ya estás unido a esa partida!',
  'textJoined': 'Te has unido a la partida',
  'textLevel': 'Nivel',
  'textYouNeedToJoin': 'Para invitar a un amigo estar unido!',
  'textChallengeFriend': 'Invitar a amigos',
  'textTeam': 'Equipo',
  'textSetResult': 'Guardar Resultado',
  'textLeaveGame': 'Salir de la partida',
  'textYourLeftTheGame': 'Has salido de la partida',
  'textYouHaveInvitedAllYourFriends': 'No hemos podido econtrar amigos a los que invitar',
  'textInvitationSent': 'Invitación enviada',
  'textCouldNotSendInvitation': 'No se ha podido enviar la invitación',
  'textInvitations': 'Invitaciones',
  'textPlay': 'Jugar!',
  'textRecord': 'Historial',
  'roundOfSixteen': 'Octavos',
  'quarterFinals': 'Cuartos',
  'semiFinals': 'Semi Final',
  'final': 'Final',
  'textLoading': 'Cargando',
  'textMyPosition': 'Mi posición',
  'textChangeTheme': 'Cambiar tema',
  'textLogout': 'Cerrar sesión',
  'textAdministration': 'Administración',
  'textWeeklyMatchesVolume': 'Volumen de partidas semanal',
  'textNoMatchesFound': 'No se ha encontrado ninguna partida',
  'textCreateUser': 'Crear Usuario',
  'textUpdateUser': 'Actualizar Usuario',
  'textCompanySettings': 'Ajustes de la empresa',
  'textWeeklySellsVolume': 'Volumen de ventas semanal',
  'textRefreshStatistics': 'Refrescar estadísticas',
  'textOptions': 'Opciones',
  'textMatchPrice': 'Precio de partida',
  'textCheckFields': 'Error, comprueba los campos',
  'textCompanyUpdated': 'Ajustes actualizados correctamente',
  'textContinue': 'Continuar',
  'textCancel': 'Cancelar',
  'textAreYouSure': '¿Estás seguro?',
  'textSaveSettings': 'Guardar ajustes',
  'textAreYouSureSaveSettings': '¿Deseas guardar los ajustes?',
  'textIsAdmin': '¿Administrador?',
  'textSearchAnUser': 'Busca un usuario',
};