import 'package:get/get.dart';

class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'loginTitle': 'Login',
      'registerTitle': 'Register',
      'textUsernameOrEmail': 'Username or Email',
      'textPassword': 'Password',
      'textRepeatPassword': 'Repeat Password',
      'textDontHaveAccount': 'Don\'t have an account? Sign Up',
      'textUsername': 'Username',
      'textEmail': 'Email',
      'textSelectYourGender': 'Select your gender',
      'textMale': 'Male',
      'textFemale': 'Female',
      'textOther': 'Other',
      'textName': 'Name',
      'textSurname': 'Surname',
      'textSelectYourLevel': 'Select your level',
      'textSelectYourPosition': 'Select your position',
      'textRightPosition': 'Right',
      'textBackhandPosition': 'Backhand',
      'textIndifferentPosition': 'Indiferent',
      'homeTitle': 'Padel',
      'textKeepMeLogged': 'Keep me logged in',
      'textFriends': 'Friends',
      'textAddFriend': 'Add friend',
      'textMyFriends': 'My friends',
      'titleProfile': 'Profile',
      'textToday': 'Today',
      'textTomorrow': 'Tomorrow',
      'textAfterTomorrow': 'After tomorrow'
    },
    'es_ES': {
      'loginTitle': 'Iniciar Sesión',
      'registerTitle': 'Registrarse',
      'textUsernameOrEmail': 'Usuario o Email',
      'textPassword': 'Contraseña',
      'textRepeatPassword': 'Repetir Contraseña',
      'textDontHaveAccount': '¿No tienes una cuenta? Registrate',
      'textUsername': 'Nombre de usuario',
      'textEmail': 'Email',
      'textSelectYourGender': 'Selecciona tu género',
      'textMale': 'Chico',
      'textFemale': 'Chica',
      'textOther': 'Otro',
      'textName': 'Nombre',
      'textSurname': 'Apellido',
      'textSelectYourLevel': 'Elige tu nivel',
      'textSelectYourPosition': 'Elige tu posicion',
      'textRightPosition': 'Derecha',
      'textBackhandPosition': 'Revés',
      'textIndifferentPosition': 'Indiferente',
      'homeTitle': 'Pádel',
      'textKeepMeLogged': 'Mantener la sesión iniciada',
      'textFriends': 'Amigos',
      'textAddFriend': 'Añadir amigo',
      'textMyFriends': 'Mis amigos',
      'titleProfile': 'Perfil',
      'textToday': 'Hoy',
      'textTomorrow': 'Mañana',
      'textAfterTomorrow': 'Pasado mañana'
    }
  };
}