import 'package:get/get.dart';

class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'loginTitle': 'Login',
      'registerTitle': 'Register',
      'textUsernameOrEmail': 'Username or Email',
      'textPassword': 'Password',
      'textRepeatPassword': 'Repeat Password',
      'textDontHaveAccount': 'Don\'t have an account? Sign Up',
      'textUsername': 'Username',
      'textEmail': 'Email',
      'textSelectYourGender': 'Select your gender',
      'textMale': 'Male',
      'textFemale': 'Female',
      'textOther': 'Other',
      'textName': 'Name',
      'textSurname': 'Surname',
      'textSelectYourLevel': 'Select your level',
      'textSelectYourPosition': 'Select your position',
      'textRightPosition': 'Right',
      'textBackhandPosition': 'Backhand',
      'textIndifferentPosition': 'Indiferent',
      'homeTitle': 'Paddle',
      'textKeepMeLogged': 'Keep me logged in',
      'textFriends': 'Friends',
      'textAddFriend': 'Add friend',
      'textMyFriends': 'My friends',
      'titleProfile': 'Profile',
      'textToday': 'Today',
      'textTomorrow': 'Tomorrow',
      'textAfterTomorrow': 'After tomorrow',
      'textAppName': 'PADEL IT',
      'textSportManagement': 'SPORT MANAGEMENT',
      'textProfile': 'Profile',
      'textTournaments': 'Tournaments',
      'textSettings': 'Settings',
      'textMatches': 'Matches',
      'textDay': 'Day',
      'textCreate': 'Create',
      'textNewMatch': 'New Match',
      'textHour': 'Hour',
      'errorAlreadyJoined': 'You are already joined to the match!',
      'textJoined': 'Joined',
      'textLevel': 'Level',
      'textYouNeedToJoin': 'For challenge you need to join first!',
      'textChallengeFriend': 'Challenge friends',
      'textTeam': 'Team',
      'textSetResult': 'Set Result',
      'textLeaveGame': 'Leave game',
      'textYourLeftTheGame': 'You left the game',
      'textYouHaveInvitedAllYourFriends': 'You have invited all your friends',
      'textInvitationSent': 'Invitation sent',
      'textCouldNotSendInvitation': 'Could not send invitation',
      'textInvitations': 'Invitations',
    },
    'es_ES': {
      'loginTitle': 'Iniciar Sesión',
      'registerTitle': 'Registrarse',
      'textUsernameOrEmail': 'Usuario o Email',
      'textPassword': 'Contraseña',
      'textRepeatPassword': 'Repetir Contraseña',
      'textDontHaveAccount': '¿No tienes una cuenta? Registrate',
      'textUsername': 'Nombre de usuario',
      'textEmail': 'Email',
      'textSelectYourGender': 'Selecciona tu género',
      'textMale': 'Chico',
      'textFemale': 'Chica',
      'textOther': 'Otro',
      'textName': 'Nombre',
      'textSurname': 'Apellido',
      'textSelectYourLevel': 'Elige tu nivel',
      'textSelectYourPosition': 'Elige tu posicion',
      'textRightPosition': 'Derecha',
      'textBackhandPosition': 'Revés',
      'textIndifferentPosition': 'Indiferente',
      'homeTitle': 'Pádel',
      'textKeepMeLogged': 'Mantener la sesión iniciada',
      'textFriends': 'Amigos',
      'textAddFriend': 'Añadir amigo',
      'textMyFriends': 'Mis amigos',
      'titleProfile': 'Perfil',
      'textToday': 'Hoy',
      'textTomorrow': 'Mañana',
      'textAfterTomorrow': 'Pasado mañana',
      'textAppName': 'PADEL IT',
      'textSportManagement': 'GESTIÓN DEPORTIVA',
      'textTournaments': 'Torneos',
      'textSettings': 'Ajustes',
      'textMatches': 'Partidas',
      'textDay': 'Día',
      'textCreate': 'Crear',
      'textNewMatch': 'Nueva Partida',
      'textHour': 'Hora',
      'errorAlreadyJoined': 'Ya estás unido a esa partida!',
      'textJoined': 'Te has unido a la partida',
      'textLevel': 'Nivel',
      'textYouNeedToJoin': 'Para invitar a un amigo estar unido!',
      'textChallengeFriend': 'Invitar a amigos',
      'textTeam': 'Equipo',
      'textSetResult': 'Guardar Resultado',
      'textLeaveGame': 'Salir de la partida',
      'textYourLeftTheGame': 'Has salido de la partida',
      'textYouHaveInvitedAllYourFriends': 'Ya has invitado a todos tus amigos!',
      'textInvitationSent': 'Invitación enviada',
      'textCouldNotSendInvitation': 'No se ha podido enviar la invitación',
      'textInvitations': 'Invitaciones',
    }
  };
}